version: "3.9"
services:

  redis1:
    image: redis:6.0.18-alpine3.17
    command: redis-server --appendonly no
    ports:
      - "3001:6379"
    networks:
      - redis-network
    deploy:
      restart_policy:
        condition: on-failure
      
  redis2:
    image: redis:6.0.18-alpine3.17
    command: redis-server --appendonly no
    ports:
      - "3002:6379"
    networks:
      - redis-network
    deploy:
      restart_policy:
        condition: on-failure

  redis3:
    image: redis:6.0.18-alpine3.17
    command: redis-server --appendonly no
    ports:
      - "3003:6379"
    networks:
      - redis-network
    deploy:
      restart_policy:
        condition: on-failure

  redis4:
    image: redis:6.0.18-alpine3.17
    command: redis-server --appendonly no
    ports:
      - "3004:6379"
    networks:
      - redis-network
    deploy:
      restart_policy:
        condition: on-failure

  redis5:
    image: redis:6.0.18-alpine3.17
    command: redis-server --appendonly no
    ports:
      - "3005:6379"
    networks:
      - redis-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  redis-network: